version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # install npm as clean
      - npm ci

  build:
    commands:
      # run build script
      - npm run build

  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id E24AK48HK2S9X6 --paths "/*"

artifacts:
  # include all files required to run the application
  files:
    - "**/*"
  base-directory: "dist"
